const wordsEn = [
  "delete",
  "hello",
  "world",
  "js",
  "react",
  "aboba",
  "system",
  "point",
  "person",
  "input",
  "user",
  "update",
  "delete",
  "insert",
  "create",
  "css",
  "style",
  "Bee",
  "restart",
  "stop",
  "run",
  "app",
  "data",
  'aardvark', 'abandon', 'ability', 'absence', 'academy', 'account', 'accuse', 'achieve', 'acid', 'acoustic',
  'acres', 'acrobat', 'actress', 'adapter', 'addict', 'adept', 'adhere', 'adjust', 'adventure', 'advertise',
  'aerial', 'aerosol', 'affair', 'african', 'afternoon', 'age', 'agile', 'agonize', 'agree', 'aircraft',
  'airfield', 'airline', 'airport', 'ajar', 'alarm', 'album', 'alcohol', 'alert', 'alien', 'align',
  'allege', 'alley', 'allow', 'almost', 'alpha', 'already', 'also', 'alter', 'always', 'amazing',
  'ambition', 'amend', 'amidst', 'amount', 'analysis', 'anatomy', 'ancient', 'angel', 'anger', 'angle',
  'animal', 'announce', 'annual', 'answer', 'anxiety', 'apex', 'apology', 'appeal', 'apple', 'apricot',
  'arcade', 'archery', 'archive', 'area', 'argue', 'arrest', 'arrive', 'artery', 'arthur', 'artistic',
  'ashamed', 'aside', 'ask', 'asleep', 'aspect', 'aspirin', 'assault', 'assert', 'assign', 'assist',
  'assume', 'asthma', 'athlete', 'atom', 'attached', 'attack', 'attempt', 'attract', 'auction', 'audit',
  'august', 'aunt', 'austin', 'author', 'auto', 'autumn', 'average', 'aviation', 'avoid', 'awake',
  'awesome', 'awful', 'awkward', 'axis', 'baby', 'bachelor', 'bacon', 'badge', 'bagel', 'baggage',
  'bake', 'balance', 'ballet', 'bamboo', 'banana', 'band', 'bang', 'bank', 'banner', 'barber',
  'bargain', 'bark', 'barrel', 'base', 'basic', 'basket', 'battle', 'beach', 'beans', 'beard',
  'beast', 'beats', 'beauty', 'become', 'beef', 'before', 'begin', 'behind', 'believe', 'below',
  'bench', 'benefit', 'best', 'betray', 'better', 'beyond', 'bicycle', 'bid', 'big', 'bike',
  'billion', 'biology', 'bird', 'birth', 'bit', 'bizarre', 'black', 'blast', 'bleak', 'blend',
  'bless', 'blind', 'blink', 'blitz', 'blob', 'block', 'blog', 'blonde', 'blood', 'blossom',
  'blouse', 'blue', 'blur', 'blush', 'board', 'boast', 'boat', 'bodies', 'bogus', 'boil',
  'bold', 'bolt', 'bonanza', 'bond', 'book', 'boost', 'border', 'boring', 'borrow', 'boss',
  'bottom', 'bounce', 'boxer', 'boy', 'bracket', 'brain', 'brand', 'brave', 'bravo', 'brawl',
  'bride', 'bridge', 'brief', 'bright', 'bring', 'brisk', 'broccoli', 'broken', 'bronze', 'brother',
  'brown', 'brush', 'bubble', 'bucket', 'buddy', 'budget', 'buffalo', 'build', 'bulb', 'bulge',
  'bulk', 'bull', 'bullet', 'bundle', 'bunker', 'burden', 'burger', 'burial', 'burn', 'burrow',
  'burst', 'bus', 'business', 'butter', 'buttermilk', 'butterfly', 'button', 'buyer', 'buzz', 'bygone',
  'byte', 'cafe', 'cage', 'cake', 'call', 'camera', 'campus', 'canal', 'cancel', 'candy',
  'cannon', 'canoe', 'canvas', 'canyon', 'capable', 'capital', 'car', 'carousel', 'carpet', 'carry',
  'cartel', 'cartoon', 'carve', 'castle', 'casual', 'catalog', 'cater', 'cattle', 'cause', 'caution',
  'cavalry', 'caviar', 'cease', 'cedar', 'celebrate', 'center', 'ceramic', 'champion', 'change', 'chaos',
  'chap', 'charge', 'chart', 'chase', 'cheat', 'check', 'cheek', 'cheer', 'cheese', 'chef',
  'cherry', 'chevron', 'chick', 'chief', 'child', 'choice', 'choose', 'chronic', 'chuckle', 'chunk',
  'churn', 'cider', 'cinema', 'circle', 'citizen', 'city', 'civil', 'claim', 'clap', 'clarify',
  'clash', 'clasp', 'classic', 'clay', 'clean', 'cleric', 'cling', 'clinic', 'clip', 'clock',
  'closet', 'cloud', 'clown', 'club', 'clump', 'cluster', 'clutch', 'coach', 'coast', 'coconut',
  'code', 'coffee', 'cohesive', 'coin', 'coke', 'cola', 'cold', 'collect', 'colony', 'color',
  'combat', 'combine', 'come', 'comfort', 'comic', 'common', 'company', 'compare', 'compete', 'compile',
  'complex', 'computer', 'cone', 'confess', 'confirm', 'congress', 'connect', 'consist', 'consult', 'contain',
  'control', 'convince', 'cook', 'cool', 'copper', 'copy', 'coral', 'corner', 'correct', 'cost',
  
];





export default wordsEn;

